### PR TITLE
Add support for Symfony 4.4 and 5.0

### PR DESCRIPTION
**Pull request by chq81**
Hi @kunicmarko20,
as I am currently upgrading my application to symfony 4.4, I adapted the stamp configuration to the ones changed.
I would appreciate feedback :)

Cheers
Christoph

### CODE REVIEW

**Comment by kunicmarko20** [comment]
Hey @chq81,

Thank you for submitting this PR, but this will kill support for anyone < 4.4, any way we can keep supporting 4.3+?

**Comment by chq81** [comment]
Hey,
I reckoned that everyone using < 4.4 is supposed to stay with 0.2.3, as it is indeed a BC break. Isn't that the case for most of the libraries out there that you do not upgrade if you are not matching the constraints?

**Comment by kunicmarko20** [comment]
Yes, but then if there needs to be an update for anyone < 4.4, there isn't a way to do that? I guess this could be a 1.0.0 release for 4.4 and 5.0, and the. 0.*.* stays for < 4.4

**Comment by chq81** [comment]
Yeah, correct. That's how i would handle it if it's fine for you. For example Symfony also keeps 4.4 as LTS support so they will need to release in the 4.4.* constraint, but they also have > 5.0.

**Comment by kunicmarko20** [comment]
@chq81 just did a 1.0.0 release https://github.com/kunicmarko20/jms-messenger-adapter/releases/tag/1.0.0, from now on 1.0.0 will be Symfony 4.4 and 5.0 releases, anything < 1.0.0 will be for Symfony 4.3 (until EOL comes for that version).

**Comment by chq81** [comment]
@kunicmarko20 Thank you very much!

**Pull request merged**
