### PR TITLE
Added symfony 5.1, changed type of Exception from Interface to concrete implementation

### PR DESCRIPTION
**Pull request by chq81**

### CODE REVIEW

**Comment by kunicmarko20** [comment]
There is a conflict, could you resolve that please and I can merge it?

**Comment by chq81** [comment]
Hey @kunicmarko20, I think I resolved the conflict. Hope you can merge now. Thanks!

**Review by kunicmarko20 — APPROVED** [review]

**Comment by kunicmarko20** [comment]
Thank you for your work, here is a new release https://github.com/kunicmarko20/jms-messenger-adapter/releases/tag/1.0.2

**Comment by chq81** [comment]
Thanks!

**Pull request merged**
